### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Iron4dam** [yizt/Grad-CAM.pytorch#1]
我在用GuidedBackPropagation的时候gradient是None出现了这个error：
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-f5189ca71dcc> in <module>
      1 gbp = GuidedBackPropagation(model)
----> 2 gbp.__call__(x)

<ipython-input-8-b837947b3c16> in __call__(self, inputs, index)
     34         target.backward()
     35 
---> 36         return inputs.grad[0]  # [3,H,W]

TypeError: 'NoneType' object is not subscriptable
```
模型是ResNet34只改变了第一层kernel的channel从3变成了4，load或者不load state_dict都有这个问题，想请教一下问题出在哪里，谢谢！

**Comment by yizt** [comment]
@Iron4dam 感谢您的反馈;在main.py中增加了如下代码;测试resnet34没有错误；不清楚您是怎么改动channel数的, 可否详细描述下，谢谢！
```
    elif net_name in ['resnet34']:
        net = models.resnet34(pretrained=pretrain)
```

**Comment by Iron4dam** [comment]
@yizt 感谢回复！我的model是：
```
model = models.resnet34(pretrained=True)

kernel = model.conv1.weight
new_conv = nn.Conv2d(4, 64, kernel_size=7, stride=2, padding=3, bias=False)
with torch.no_grad():
    new_conv.weight[:,:] = torch.stack([torch.mean(kernel, 1)]*4, dim=1)
model.conv1 = new_conv

model.fc = torch.nn.Linear(512, 2)
```
input也是四个channel（类似RGBY），dimension是（1，4，2048，2048）

**Comment by yizt** [comment]
@Iron4dam 您，我测试报了如下错：
```
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    main(arguments)
  File "main.py", line 172, in main
    mask = grad_cam(inputs, args.class_id)  # cam mask
  File "E:\pyspace\Grad-CAM.pytorch\interpretability\grad_cam.py", line 60, in __call__
    output = self.net(inputs)  # [1,num_classes]
  File "F:\Anaconda3-5.0.1\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\Anaconda3-5.0.1\envs\pytorch\lib\site-packages\torchvision\models\resnet.py", line 196, in forward
    x = self.conv1(x)
  File "F:\Anaconda3-5.0.1\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\Anaconda3-5.0.1\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "F:\Anaconda3-5.0.1\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'weight'
```

**Comment by Iron4dam** [comment]
@yizt 这个我好像没有遇到，不过我加了一个`inputs.requires_grad=True`就解决了之前的问题，谢谢！
