### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (224,224,4) (3,) (224,224,4) 

### ISSUE THREAD

**Issue by kunyaoli** [yizt/Grad-CAM.pytorch#20]
ValueError: operands could not be broadcast together with shapes (224,224,4) (3,) (224,224,4)   加载自己模型的报错，修改了get_net(net_name, weight_path=None)部分

**Comment by kunyaoli** [comment]
Traceback (most recent call last):
  File "E:/chrome下载/Grad-CAM.pytorch-master/Grad-CAM.pytorch-master/main.py", line 198, in <module>
    main(arguments)
  File "E:/chrome下载/Grad-CAM.pytorch-master/Grad-CAM.pytorch-master/main.py", line 151, in main
    inputs = prepare_input(img)
  File "E:/chrome下载/Grad-CAM.pytorch-master/Grad-CAM.pytorch-master/main.py", line 90, in prepare_input
    image -= means
ValueError: operands could not be broadcast together with shapes (224,224,4) (3,) (224,224,4)

**Comment by kunyaoli** [comment]
已经修改好了，主要是原图是采用的png格式存储。全部修改成jpg，就可以了。感谢大佬
