### ISSUE TITLE
save image error

### ISSUE THREAD

**Issue by xiezheng-cs** [yizt/Grad-CAM.pytorch#3]
Traceback (most recent call last):
  File "D:/2019Pytorch_Programs/Papers_codes/efficient-finetuning/visualization/main.py", line 215, in <module>
    main(arguments)
  File "D:/2019Pytorch_Programs/Papers_codes/efficient-finetuning/visualization/main.py", line 194, in main
    save_image(image_dict, os.path.basename(args.image_path), args.network, args.output_dir)
  File "D:/2019Pytorch_Programs/Papers_codes/efficient-finetuning/visualization/main.py", line 153, in save_image
    io.imsave(os.path.join(output_dir, '{}-{}-{}.jpg'.format(prefix, network, key)), image)
  File "D:\Anaconda3\lib\site-packages\skimage\io\_io.py", line 139, in imsave
    if is_low_contrast(arr):
  File "D:\Anaconda3\lib\site-packages\skimage\exposure\exposure.py", line 501, in is_low_contrast
    image = rgb2gray(image)
  File "D:\Anaconda3\lib\site-packages\skimage\color\colorconv.py", line 804, in rgb2gray
    rgb = _prepare_colorarray(rgb[..., :3])
  File "D:\Anaconda3\lib\site-packages\skimage\color\colorconv.py", line 158, in _prepare_colorarray
    return dtype.img_as_float(arr)
  File "D:\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 378, in img_as_float64
    return convert(image, np.float64, force_copy)
  File "D:\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 244, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.

**Comment by txfs1926** [comment]
Same here when running the example command.

**Comment by yizt** [comment]
@txfs1926 @xiezheng-cs 我测试只有警告，没有报错，如下所示；目前已经修正没有改警告
`/Users/yizuotian/miniconda2/envs/pytorch/lib/python3.6/site-packages/skimage/io/_io.py:141: UserWarning: results/pic1-shufflenet_v2-gb.jpg is a low contrast image
  warn('%s is a low contrast image' % fname)
Lossy conversion from float32 to uint8. Range [-0.569231390953064, 0.3581102788448334]. Convert image to uint8 prior to saving to suppress this warning.
`
